version: "3.8"

networks:
  default:
    name: typingrealm
    external: true

services:
  habits-web:
    image: ghcr.io/ewancoder/habits-web:main
    container_name: habits-web
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  habits-api:
    image: ghcr.io/ewancoder/habits-api:main
    container_name: habits-api
    volumes:
      - /data/habits/data:/app/data
      - /data/habits/dataprotection:/app/dataprotection
      - /root/dp.pfx:/app/dp.pfx
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/habits/secrets.env
